#!/bin/bash

# PROD
# kubectl 2>/dev/null get ing -ojson | jq -r '.items[] | select(.metadata.name | contains("pwa")) | .spec | .rules[] | .host'

# QA
# kubectl 2>/dev/null get ing -ojson | jq -r '.items[] | select(.metadata.name | contains("pwa")) | .spec | .rules[] | .host'

aws cloudfront list-distributions | jq -r '.DistributionList.Items[] | .Aliases.Items[] | select(. | test("^[a-z].*-pwa.\w+.(?:cm|qa)"))' | tee
